#!/bin/bash

ln -si $PWD/.vimrc $HOME/
ln -si $PWD/.gitconfig $HOME/
ln -si $PWD/.gitignore $HOME/
ln -si $PWD/.bash_profile $HOME/
ln -si $PWD/.vim $HOME/
ln -si $PWD/bin $HOME/

read -p "rm/git: install/replace Vundle? " replace_vundle

if [ $replace_vundle == "y" ]; then
	rm -rf .vim/bundle/Vundle.vim
	git clone https://github.com/gmarik/Vundle.vim.git .vim/bundle/Vundle.vim
fi

vi +PluginInstall +qall
